apiVersion: v1
kind: Namespace
metadata:
  name: haep

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: haep
type: Opaque
data:
  password-admin-secret: c3VwZXItc2VjcmV0LXBhc3N3b3JkCg== 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  namespace: haep
  labels:
    app: phpmyadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-deployment
  template:
    metadata:
      labels:
        app: phpmyadmin-deployment
    spec:
      containers:
        - name: phpmyadmin
          image: udecdj2022/phpmyadmin:vpipeline
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql-service
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password-admin-secret
