apiVersion: v1
kind: Namespace
metadata:
  name: haep

    #---
    #apiVersion: v1
    #kind: Secret
    #metadata:
    #name: mysql-secrets
    #namespace: haep
    #type: Opaque
    #data:
    #password-admin-secret: c3VwZXItc2VjcmV0LXBhc3N3b3JkCg== 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  namespace: haep
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: udecdj2022/phpmyadmin:vpipeline
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql-service
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password-mysql-secret
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: haep
spec:
  type: ClusterIP
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

