apiVersion: v1
kind: Namespace
metadata:
  name: haep
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  namespace: haep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: udecdj2022/phpmyadmin:vpipeline
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql-service
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password
      
          volumeMounts:
            - name: sessions
              mountPath: /sessions
      volumes:
        - name: sessions
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: haep
spec:
  type: ClusterIP
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

