apiVersion: v1
kind: Namespace
metadata:
  name: haep

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: haep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD  
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-disk

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: haep
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306

