apiVersion: v1
kind: Namespace
metadata:
  name: haep

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-disk
  namespace: haep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: haep
type: Opaque
data:
  password-mysql-secret: c3VwZXItc2VjcmV0LXBhc3N3b3Jk


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: haep
  labels:
    app: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-deployment
  template:
    metadata:
      labels:
        app: mysql-deployment
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              subPath: "mysql"
              name: mysql-data
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password-mysql-secret
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-disk

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: haep
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

